# Generated by Django 2.2.10 on 2020-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200602_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
