# Generated by Django 2.2.10 on 2020-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_menu'),
        ('cart', '0005_auto_20200604_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='extra',
        ),
        migrations.AddField(
            model_name='additional',
            name='extra',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Extra'),
        ),
        migrations.RemoveField(
            model_name='additional',
            name='toppings',
        ),
        migrations.AddField(
            model_name='additional',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Toppings'),
        ),
    ]
