# Generated by Django 2.2.10 on 2020-06-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_menu'),
        ('cart', '0007_auto_20200605_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='extra',
        ),
        migrations.AddField(
            model_name='additional',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Extra'),
        ),
        migrations.RemoveField(
            model_name='additional',
            name='toppings',
        ),
        migrations.AddField(
            model_name='additional',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional',
        ),
        migrations.AddField(
            model_name='product',
            name='additional',
            field=models.ManyToManyField(to='cart.Additional'),
        ),
    ]
