# Generated by Django 2.2.10 on 2020-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_menu'),
        ('cart', '0010_auto_20200605_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='extra',
        ),
        migrations.AddField(
            model_name='additional',
            name='extra',
            field=models.ManyToManyField(to='orders.Extra'),
        ),
        migrations.RemoveField(
            model_name='additional',
            name='toppings',
        ),
        migrations.AddField(
            model_name='additional',
            name='toppings',
            field=models.ManyToManyField(to='orders.Toppings'),
        ),
    ]
