# Generated by Django 2.2.10 on 2020-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20200606_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='additional',
            field=models.BooleanField(default=False),
        ),
    ]
