# Generated by Django 2.2.10 on 2020-06-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_additional_additional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='additionals',
            new_name='additional',
        ),
    ]
