# Generated by Django 2.2.10 on 2020-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20200606_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='extra',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Extra'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Toppings'),
        ),
    ]
