# Generated by Django 2.2.10 on 2020-06-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order_items',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
