# Generated by Django 2.0.3 on 2020-05-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(choices=[('Reg', 'Regular'), ('Sl', 'Sicilian')], max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=20)),
                ('topping', models.CharField(choices=[('C', 'Cheese'), ('one', '1 topping'), ('two', '2 toppings'), ('three', '3 toppings'), ('SP', 'Special')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
