# Generated by Django 2.2.10 on 2020-05-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinnerplatters_pastas_salads_subs_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Toppings'),
        ),
    ]
