# Generated by Django 2.2.10 on 2020-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizza_topping_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping_type',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('none', 'None'), ('one', '1 topping'), ('two', '2 toppings'), ('three', '3 toppings'), ('five', '5 toppings')], max_length=20),
        ),
    ]
