# Generated by Django 2.2.10 on 2020-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200509_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='extras',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=20),
        ),
        migrations.AddField(
            model_name='subs',
            name='price_of_extra',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('C', 'Cheese'), ('one', '1 topping'), ('two', '2 toppings'), ('three', '3 toppings'), ('five', '5 toppings')], max_length=20),
        ),
    ]
