# Generated by Django 2.2.10 on 2020-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200509_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='extras',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subs',
            name='price_of_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
