# Generated by Django 2.2.10 on 2020-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200514_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatters',
            name='platterty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
