# Generated by Django 2.2.10 on 2020-05-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dinnerplatters_platterty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatters',
            name='platterty',
        ),
        migrations.RemoveField(
            model_name='dinnerplatters',
            name='size',
        ),
        migrations.RemoveField(
            model_name='platter_item',
            name='price',
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='platter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Platter_Item'),
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platter_item',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='platter_item',
            name='platter',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
