# Generated by Django 2.2.10 on 2020-05-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200514_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs_items',
            name='sub_choice',
        ),
    ]
