# Generated by Django 2.2.10 on 2020-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200514_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatters',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], default=(('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')), max_length=20),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=20),
        ),
        migrations.DeleteModel(
            name='No_of_Topping',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
