# Generated by Django 2.2.10 on 2020-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200514_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular_pizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='subs_items',
            name='extra',
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=20),
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], default=(('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')), max_length=20),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=20),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], default=(('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')), max_length=20),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
