# Generated by Django 2.2.10 on 2020-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200523_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatters',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=50),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pastas',
            name='pasta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platter_item',
            name='platter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=50),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], default=(('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')), max_length=50),
        ),
        migrations.AlterField(
            model_name='salads',
            name='salad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=50),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], default=(('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')), max_length=50),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=(('Small', 'Small'), ('Large', 'Large')), max_length=50),
        ),
        migrations.AlterField(
            model_name='subs_items',
            name='sub',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='topping',
            field=models.CharField(max_length=50),
        ),
    ]
