# Generated by Django 2.2.10 on 2020-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200523_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=50),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One topping', '1 topping'), ('Two toppings', '2 toppings'), ('Three toppings', '3 toppings'), ('Five toppings', '5 toppings')], max_length=50),
        ),
    ]
