# Generated by Django 2.2.10 on 2020-05-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200523_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platter_Item',
            new_name='PlatterItem',
        ),
        migrations.RenameModel(
            old_name='Subs_Items',
            new_name='SubsItems',
        ),
    ]
