# Generated by Django 2.2.10 on 2020-05-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200529_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatterItem',
            new_name='Platter_Item',
        ),
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='platter',
            new_name='platter_item',
        ),
    ]
