# Generated by Django 2.2.10 on 2020-05-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200529_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One', '1 topping'), ('Two', '2 toppings'), ('Three', '3 toppings'), ('Five', '5 toppings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('One', '1 topping'), ('Two', '2 toppings'), ('Three', '3 toppings'), ('Five', '5 toppings')], max_length=50),
        ),
    ]
